# NexT Theme Configuration
# Docs: https://theme-next.js.org/docs/

scheme: Mist

darkmode: false

menu:
  首页: / || fa fa-home
  归档: /archives/ || fa fa-archive
  分类: /categories/ || fa fa-th
  标签: /tags/ || fa fa-tags

menu_settings:
  icons: true
  badges: false

sidebar:
  position: left
  display: post

avatar:
  url: /img/didaclass-math-hero.png
  rounded: true
  rotated: false

site_state: true

toc:
  enable: true
  number: true
  wrap: false
  expand_all: false
  max_depth: 3

post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: false
  categories: true

back2top:
  enable: true
  sidebar: true
  scrollpercent: true

bookmark:
  enable: true
  color: "#2f80ed"
  save: auto

footer:
  icon:
    name: fa fa-graduation-cap
    animated: false
    color: "#2f80ed"
  powered: false

math:
  every_page: true
  mathjax:
    enable: true
    tags: none
  katex:
    enable: false
    copy_tex: false

local_search:
  enable: true
  top_n_per_article: 2
  unescape: false
  preload: false
